name: Nightly dev release

on:
  schedule: # UTC at 0300
    - cron: "0 5 * * *"
  workflow_dispatch:
      
env:
  MAIN_PYTHON_VERSION: '3.10'

jobs:
  nightly-release:
    name: Nightly release package
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Append date to version tags
        run: |
          PACKAGE_DATE=$(date +'%Y%m%d')
          sed -i "1s/$/-$PACKAGE_DATE/" ansys/api/geometry/VERSION

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install build requirements
        run: |
          pip install -U pip
          pip install build

      - name: Build
        run: python -m build

      - name: Install
        run: pip install dist/*.whl

      - name: Test import
        run: |
          mkdir tmp
          cd tmp
          python -c "import ansys.api.geometry.v0; print('Successfully imported ansys.api.geometry.v0')"
          python -c "from ansys.api.geometry import __version__; print(__version__)"

      - name: Upload to Private PyPi
        run: |
          pip install twine
          twine upload --skip-existing ./**/*.whl
          twine upload --skip-existing ./**/*.tar.gz
        env:
          TWINE_USERNAME: PAT
          TWINE_PASSWORD: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }} 
          TWINE_REPOSITORY_URL: https://pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/upload

      - name: Upload packages
        uses: actions/upload-artifact@v3
        with:
          name: ansys-api-geometry-packages
          path: dist/
          retention-days: 7

